	LIST P=16F877
	INCLUDE "P16F877.INC"
		SAYAC2	EQU	H'0031'
		SAYAC3	EQU H'0033'
		SAYAC1	EQU	H'0035'
		LCD_TMP0 EQU H'0036'
		LCD_DATA EQU h'0037'
		ORG 0
		GOTO ANA_PROGRAM
		ORG 4
	LCD_SEND_CHAR						
	MOVWF	LCD_DATA	
	SWAPF	LCD_DATA, W		
	BANKSEL PORTB
	BSF PORTB,4			
	CALL	LCD_NYBBLEOUT
	MOVF	LCD_DATA, W		
	BANKSEL PORTB	
	BSF PORTB,4		;RS = 1 ( veri gönderme modu )
	CALL	LCD_NYBBLEOUT
	RETURN
	TEMIZLE:
		MOVLW H'02'
		CALL LCD_SEND_CMD  
		MOVLW	H'0C'
		CALL LCD_SEND_CMD  
		MOVLW	H'01'
		CALL LCD_SEND_CMD  
		MOVLW	H'28'
		CALL LCD_SEND_CMD  
		MOVLW	H'0F'
		CALL LCD_SEND_CMD  
		MOVLW	H'06'
		CALL LCD_SEND_CMD  
	RETURN
	LCD_SEND_CMD       	         	
		MOVWF	LCD_DATA	 	
		SWAPF	LCD_DATA, W   	
		BANKSEL PORTB
		BCF PORTB,4		
		CALL	LCD_NYBBLEOUT
		MOVF	LCD_DATA, W	
		BANKSEL PORTB
		BCF PORTB,4		
		CALL	LCD_NYBBLEOUT		
		RETURN
	LCD_NYBBLEOUT                      
		ANDLW	0x0F			
		MOVWF	LCD_TMP0	
		MOVF	PORTB,W				
		ANDLW	0xF0							
		IORWF	LCD_TMP0, W		
		MOVWF	PORTB 	
		BANKSEL PORTB 	
		BSF	PORTB,5 
		CALL GECIKME_LCD
		BCF	PORTB,5		
		CALL GECIKME_LCD
		RETURN
	GECIKME:
		MOVLW	H'FF'
		MOVWF	SAYAC1
	DON1:
		MOVLW	H'FF'
		MOVWF	SAYAC2
	DON2:
		DECFSZ	SAYAC2,F
		GOTO	DON2
		DECFSZ	SAYAC1,F
		GOTO	DON1
		RETURN
	GECIKME_LCD:
		MOVLW	H'9F'
		MOVWF	SAYAC1
	DON1_LCD:
		MOVLW	H'FF'
		MOVWF	SAYAC2
	DON2_LCD:
		DECFSZ	SAYAC2,F
		GOTO	DON2_LCD
		DECFSZ	SAYAC1,F
		GOTO	DON1_LCD
		RETURN
	SATIR1:
		MOVLW H'80'
		CALL LCD_SEND_CMD  
		RETURN	
	ANA_PROGRAM:
		BCF	STATUS,6
		BSF	STATUS,5
		CLRF TRISB
		MOVLW H'F0'
		MOVWF TRISC
		BCF	STATUS,5
		MOVLW B'00001111'
		MOVWF PORTC
		CLRF SAYAC3
		CLRF PORTB
		CALL TEMIZLE
		CALL SATIR1
	SONSUZ:
		CALL GECIKME		
		BTFSC PORTC,4
		GOTO SUTUN1
		BTFSC PORTC,5
		GOTO SUTUN2
		BTFSC PORTC,6
		GOTO SUTUN3
		BTFSC PORTC,7
		GOTO SUTUN4
		GOTO SONSUZ
	SUTUN1:
		MOVLW H'01'
		MOVWF PORTC
		BTFSC PORTC,4
		GOTO BIR
		MOVLW H'02'
		MOVWF PORTC
		BTFSC PORTC,4
		GOTO DORT
		MOVLW H'04'
		MOVWF PORTC
		BTFSC PORTC,4
		GOTO YEDI
		MOVLW H'08'
		MOVWF PORTC
		BTFSC PORTC,4
		GOTO YILDIZ
		GOTO SONSUZ
	BIR:
		MOVLW A'1'
		CALL LCD_SEND_CHAR
		MOVLW H'0F'
		MOVWF PORTC
	BTFSS SAYAC3,4
		GOTO SONSUZ
		MOVLW H'02'
		CALL LCD_SEND_CMD  
		CLRF SAYAC3
		GOTO SONSUZ
	DORT:
		MOVLW A'4'
		CALL LCD_SEND_CHAR
		MOVLW H'0F'
		MOVWF PORTC
	BTFSS SAYAC3,4
		GOTO SONSUZ
		MOVLW H'02'
		CALL LCD_SEND_CMD  
		CLRF SAYAC3
		GOTO SONSUZ
	YEDI:
		MOVLW A'7'
		CALL LCD_SEND_CHAR
		MOVLW H'FF'
		MOVWF PORTC
	BTFSS SAYAC3,4
		GOTO SONSUZ
		MOVLW H'02'
		CALL LCD_SEND_CMD  
		CLRF SAYAC3
		GOTO SONSUZ
	YILDIZ:
		MOVLW A'*'
		CALL LCD_SEND_CHAR
		MOVLW H'FF'
		MOVWF PORTC
	BTFSS SAYAC3,4
		GOTO SONSUZ
		MOVLW H'02'
		CALL LCD_SEND_CMD  
		CLRF SAYAC3
		GOTO SONSUZ
	SUTUN2:
		INCF SAYAC3
		MOVLW H'01'
		MOVWF PORTC
		BTFSC PORTC,5
		GOTO IKI
		MOVLW H'02'
		MOVWF PORTC
		BTFSC PORTC,5
		GOTO BES
		MOVLW H'04'
		MOVWF PORTC
		BTFSC PORTC,5
		GOTO SEKIZ
		MOVLW H'08'
		MOVWF PORTC
		BTFSC PORTC,5
		GOTO SIFIR
		GOTO SONSUZ
	IKI:
		MOVLW A'2'
		CALL LCD_SEND_CHAR
		MOVLW H'FF'
		MOVWF PORTC
		BTFSS SAYAC3,4
		GOTO SONSUZ
		MOVLW H'02'
		CALL LCD_SEND_CMD  
		CLRF SAYAC3
		GOTO SONSUZ
	BES:
		MOVLW A'5'
		CALL LCD_SEND_CHAR
		MOVLW H'0F'
		MOVWF PORTC
	BTFSS SAYAC3,4
		GOTO SONSUZ
		MOVLW H'02'
		CALL LCD_SEND_CMD  
		CLRF SAYAC3
		GOTO SONSUZ
		
	SEKIZ:
		MOVLW A'8'
		CALL LCD_SEND_CHAR
		MOVLW H'FF'
		MOVWF PORTC
		BTFSS SAYAC3,4
		GOTO SONSUZ
		MOVLW H'02'
		CALL LCD_SEND_CMD  
		CLRF SAYAC3
		GOTO SONSUZ

	SIFIR:
		MOVLW A'0'
		CALL LCD_SEND_CHAR
		MOVLW H'FF'
		MOVWF PORTC
		BTFSS SAYAC3,4
		GOTO SONSUZ
		MOVLW H'02'
		CALL LCD_SEND_CMD  
		CLRF SAYAC3
		GOTO SONSUZ
	SUTUN3:
INCF SAYAC3
		MOVLW H'01'
		MOVWF PORTC
		BTFSC PORTC,6
		GOTO UC
		MOVLW H'02'
		MOVWF PORTC
		BTFSC PORTC,6
		GOTO ALTI
		MOVLW H'04'
		MOVWF PORTC
		BTFSC PORTC,6
		GOTO DOKUZ
		MOVLW H'08'
		MOVWF PORTC
		BTFSC PORTC,6
		GOTO KARE
		
		GOTO SONSUZ

	UC:
		MOVLW A'3'
		CALL LCD_SEND_CHAR
		MOVLW H'FF'
		MOVWF PORTC
	BTFSS SAYAC3,4
		GOTO SONSUZ
		MOVLW H'02'
		CALL LCD_SEND_CMD  
		CLRF SAYAC3
		GOTO SONSUZ
	ALTI:
		MOVLW A'6'
		CALL LCD_SEND_CHAR
		MOVLW H'0F'
		MOVWF PORTC
	BTFSS SAYAC3,4
		GOTO SONSUZ
		MOVLW H'02'
		CALL LCD_SEND_CMD  
		CLRF SAYAC3
		GOTO SONSUZ
		
	DOKUZ:
		MOVLW A'9'
		CALL LCD_SEND_CHAR
		MOVLW H'FF'
		MOVWF PORTC
	BTFSS SAYAC3,4
		GOTO SONSUZ
		MOVLW H'02'
		CALL LCD_SEND_CMD  
		CLRF SAYAC3
		GOTO SONSUZ

	KARE:
		MOVLW A'#'
		CALL LCD_SEND_CHAR
		MOVLW H'FF'
		MOVWF PORTC
	BTFSS SAYAC3,4
		GOTO SONSUZ
		MOVLW H'02'
		CALL LCD_SEND_CMD  
		CLRF SAYAC3
		GOTO SONSUZ

	SUTUN4:
INCF SAYAC3
		MOVLW H'01'
		MOVWF PORTC
		BTFSC PORTC,7
		GOTO AA
		MOVLW H'02'
		MOVWF PORTC
		BTFSC PORTC,7
		GOTO BB
		MOVLW H'04'
		MOVWF PORTC
		BTFSC PORTC,7
		GOTO CC
		MOVLW H'08'
		MOVWF PORTC
		BTFSC PORTC,7
		GOTO DD
		
		GOTO SONSUZ

	AA:
		MOVLW A'A'
		CALL LCD_SEND_CHAR
		MOVLW H'FF'
		MOVWF PORTC
		BTFSS SAYAC3,4
		GOTO SONSUZ
		MOVLW H'02'
		CALL LCD_SEND_CMD  
		CLRF SAYAC3
		GOTO SONSUZ
	BB:
		MOVLW A'B'
		CALL LCD_SEND_CHAR
		MOVLW H'0F'
		MOVWF PORTC
		BTFSS SAYAC3,4
		GOTO SONSUZ
		MOVLW H'02'
		CALL LCD_SEND_CMD  
		CLRF SAYAC3
		GOTO SONSUZ
		
	CC:
		MOVLW A'C'
		CALL LCD_SEND_CHAR
		MOVLW H'FF'
		MOVWF PORTC
		BTFSS SAYAC3,4
		GOTO SONSUZ
		MOVLW H'02'
		CALL LCD_SEND_CMD  
		CLRF SAYAC3
		GOTO SONSUZ
	DD:
		MOVLW A'D'
		CALL LCD_SEND_CHAR
		MOVLW H'FF'
		MOVWF PORTC
		BTFSS SAYAC3,4
		GOTO SONSUZ
		MOVLW H'02'
		CALL LCD_SEND_CMD  
		CLRF SAYAC3
		GOTO SONSUZ
	END
	
