;**********************************************************************
;                                                                     *
;    Filename:	    lcdlib.inc                                        *
;    Date:                                                            *
;    Author:        el@jap.hu                                         *
;    Company:       http://jap.hu/                                    *
;                                                                     * 
;**********************************************************************

	EXTERN lcd_init, lcd_strout, lcd_decout, lcd_hexout, lcd_cmdout
	EXTERN lcd_chrout, lcd_delay5ms
